on: [push, pull_request]
name: Ansible modules yamale
jobs:
  test:
    name: "Test Ansible Modules"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install requirements
      run: |
            sudo apt update && sudo apt install python3 python3-pip python3-setuptools
            sudo -H pip3 install pytest pytest-mock ansible
    - name: Run tests for python modules
      run: pytest
